version: '3.4'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes: 
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - "POSTGRES_PASSWORD=password"
      - "USER_PASSWORD=userpassword"    
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postuser
      - PGHOST=postgres
      - PGDATABASE=db
      - PGPASSWORD=userpassword
      - PGPORT=5432
    ports:
      - '8000:5000'
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
